export { default as SideBar } from "./SideBar/SideBar";
export { default as HomeSection } from "./HomeSection/HomeSection";
export { default as AboutSection } from "./AboutSection/AboutSection";
export { default as ServicesSection } from "./ServicesSection/ServicesSection";
export { default as ExperienceSection } from "./ ExperienceSection/ ExperienceSection";
export { default as SkillsSection } from "./SkillsSection/SkillsSection";
export { default as WorkSection } from "./WorkSection/WorkSection";
export { default as EducationSection } from "./EducationSection/EducationSection";
export { default as ContactSection } from "./ContactSection/ContactSection";
export { default as Footer } from "./Footer/Footer";
export { default as InterestsSection } from "./InterestsSection/InterestsSection";
